#!/usr/bin/perl

# find out which version of busybox we have; this is taken from the name
# of this directory
$uclibc_version = `basename \`pwd\``;
chomp $uclibc_version;
$uclibc_version =~ s/uClibc-//;

#
# first extract all configuration files from the original source tree
#

@configfiles = `find ../../build/uClibc-$uclibc_version -name "Config.*"`;

while($_ = shift @configfiles) {
	chomp $_;
	my $filename = $_;   $filename =~ s/(.*\/uClibc.*?)\/(.*$)/$2/;
	my $dir = $filename; $dir      =~ s/(.*\/)(.*$)/$1/;
	system("mkdir -p $dir");
	system("../../scripts/mkprefix -v -p UC_ < $_ > $filename");
}


#
# fix some entries 
# 

print "---------------------------------------------------------------------\n";
print "Fixing some stuff...\n";
print "---------------------------------------------------------------------\n";

@fixfiles = `find . -name "Config.*"`;

while($file = shift @fixfiles) {

    print "$file";
    
    open (FILE, "$file");
    @file = <FILE>;
    close FILE;

    for (@file) { $_ =~ s/^source \"(.*)\"$/source \"config\/uClibc-$uclibc_version\/$1\"/g; }
    for (@file) { $_ =~ s/^mainmenu (.*$)/\# mainmenu $1/g;                                  }
    for (@file) { $_ =~ s/^(menu .*)$/$1\n  depends on UCLIBC/g;                             }
				     
    open (FILE, ">$file");
    print FILE @file;
    close FILE;
}
