#!/bin/sh
#
# /etc/init.d/rcS
#
# Configuration for Auerswald Innokom
#
# 2002/10/03    Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "PTXDIST - prerelease 2003-03-04"
echo "Please report problems with this software"
echo "to Robert Schwebel <r.schwebel@pengutronix.de>"
echo 

echo -n "mounting filesystems..."
mount -a 
echo "done."
