#! /bin/sh
#
# /etc/init.d/banner
#
# Configuration for Auerswald Innokom
#
# 2002/10/03    Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "PTXDIST - prerelease 2003-07-15"
echo "Please report problems with this software"
echo "to Robert Schwebel <r.schwebel@pengutronix.de>"
echo 
