#! /bin/sh
#
# /etc/init.d/mount-local
#
# Configuration for Auerswald Innokom
#
# 2002/10/03    Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "mounting filesystems... "
mount -a 
echo "done."
