#! /bin/sh
#
# /etc/init.d/syslog
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Author: Kai-Uwe Bloem, <linux-development@auerswald.de>

echo -n "starting the system logger... "
/sbin/klogd
echo 0 >/proc/sys/kernel/printk
/sbin/syslogd
echo "done."
