#!/bin/sh
#
# /etc/init.d/penguzilla
#
# Configuration for BMW
#
# 2004/03/28 Robert Schwebel <r.schwebel@pengutronix.de>
#

case $1 in

	start)
		echo "preparing environment for penguzilla..."
		export GTK_MODULES=libgail.so
		export GTK_PATH=/usr/lib
		export GNOME_ACCESSIBILITY=1
		export GTK_ACCESSIBILITY=1
		export MOZILLA_FIVE_HOME=/usr/lib/mozilla-1.6
		export LD_LIBRARY_PATH=/usr/lib/mozilla-1.6
		export PENGUDRIVE=/dev/input/event1
		export PENGUDRIVE_WIDTH=15
		export GDK_USE_XFT=1
		echo "starting penguzilla..."
		# penguzilla `[ "$2" = "silent" ] && echo "2>&1 > /dev/null"` &
		DISPLAY=:0.0 penguzilla &
		echo $! > /var/run/penguzilla.pid
                echo "done."
                ;;
        stop)
                echo "killing penguzilla ..."
                kill `cat /var/run/penguzilla.pid`
                echo "done."
                ;;
	restart)
		/etc/init.d/penguzilla stop
		/etc/init.d/penguzilla start
		;;
        *)
                echo "usage: $0 [start|stop|restart]"
                ;;
esac

