#!/bin/sh
#
# /etc/init.d/rcS
#
# Configuration for BMW
#
# 2004/02/27 Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "PTXDIST - prerelease 2004/02/27"
echo "Please report problems with this software"
echo "to Robert Schwebel <r.schwebel@pengutronix.de>"
echo 

echo -n "mounting filesystems..."
mount -a 
echo "done."

echo -n "creating links in /dev..."
ln -sf /dev/vc/0 /dev/tty0
ln -sf /dev/vc/1 /dev/tty1
ln -sf /dev/vc/2 /dev/tty2
ln -sf /dev/vc/3 /dev/tty3
ln -sf /dev/vc/4 /dev/tty4
ln -sf /dev/vc/5 /dev/tty5
ln -sf /dev/vc/6 /dev/tty6
ln -sf /dev/vc/7 /dev/tty7
ln -sf /dev/vc/8 /dev/tty8
ln -sf /dev/vc/9 /dev/tty9
ln -sf /dev/fb/0 /dev/fb0
echo "done."

echo "remounting root fs r/w"
mount /dev/root / -o remount,rw
echo "done."

/etc/init.d/syslog	start
/etc/init.d/dropbear	start
/etc/init.d/serial	start
/etc/init.d/ppp-drivers	start

# run some scripts only once for initialisation
if [ ! -f /etc/gtk-2.0/gdk-pixbuf.loaders ]; then
	echo "creating /etc/gtk-2.0/gdk-pixbuf.loaders"
	/usr/bin/gdk-pixbuf-query-loaders 		\
		/usr/lib/gdk-pixbuf-loaders/*.so > 	\
		/etc/gtk-2.0/gdk-pixbuf.loaders
fi;
if [ ! -f /etc/pango/pango.modules ]; then
	echo "creating /etc/pango/pango.modules"
	/usr/bin/pango-querymodules 			\
		/usr/lib/pango/1.4/modules/*.so	>	\
		/etc/pango/pango.modules
fi;

# /usr/X11R6/bin/xmodmap /etc/xmodmap

