#!/bin/sh
#
# /etc/init.d/serial
#
# Configuration for BMW
#
# 2004/02/27 Robert Schwebel <r.schwebel@pengutronix.de>
#

case $1 in 

	start)
		echo "loading serial drivers:"
		/sbin/modprobe serial_core
		/sbin/modprobe 8250
		/sbin/modprobe 8250_pci
		echo "done."
		;;

	stop)
		echo "removing serial drivers:"
		/sbin/rmmod 8250_pci
		/sbin/rmmod 8250
		/sbin/rmmod serial_core
		echo "done."
		;;

	*)
		echo "usage: $0 [start|stop]"
		;;

esac

