#! /bin/sh
#
# /etc/init.d/banner
#
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "@PROJECT@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@ (@DATE@)"
echo 
