#!/bin/bash

set -e
PTXDIST_SETENV_BAREBOX_ENV="${1}"
ENVTMPDIR="$(mktemp -d "${PTXDIST_TEMPDIR}/barebox_env.XXXXXX")"

# IMAGEDIR is not set if we use this script with "ptxdist test" directly
# since it comes from kwraper.
[ -z "${IMAGEDIR}" ] && export IMAGEDIR=${PTXDIST_PLATFORMDIR}/images

if [ ! -r ${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/config ]; then
	echo "ERROR: missing valid ${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/config" >&2
	exit 1
fi

tar -C "${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/" -c . \
	--exclude .svn \
	--exclude .pc \
	--exclude .git \
	--exclude "config.in" \
	--exclude "*/*~" \
	| tar -C "${ENVTMPDIR}" -x

bareboxenv -s "${ENVTMPDIR}" "${IMAGEDIR}/barebox-environment"

# only copy the image if we are called by "test setenv"
[ -n "${PTXDIST_SETENV_BAREBOX_ENV}" ] && cp "${IMAGEDIR}/barebox-environment" "${PTXDIST_SETENV_BAREBOX_ENV}"

rm -rf "${ENVTMPDIR}"
