#!/bin/bash

set -e
PTXDIST_SETENV_BAREBOX_ENV="${1}"
ENVTMPDIR="$(mktemp -d "${PTXDIST_TEMPDIR}/barebox_env.XXXXXX")"

tar -C "${PTXDIST_PLATFORMCONFIGDIR}/barebox-env/" -c . \
	--exclude .svn \
	--exclude .pc \
	--exclude .git \
	--exclude "config.in" \
	--exclude "*/*~" \
	| tar -C "${ENVTMPDIR}" -x

${PTXDIST_SYSROOT_HOST}/bin/bareboxenv -s "${ENVTMPDIR}" "${IMAGEDIR}/barebox-environment"

cp "${IMAGEDIR}/barebox-environment" "${PTXDIST_SETENV_BAREBOX_ENV}"

rm -rf "${ENVTMPDIR}"
