#!/bin/bash

set -e
PTXDIST_SETENV_U_BOOT_V2_ENV="${1}"
ENVTMPDIR="$(mktemp -d "${PTXDIST_TEMPDIR}/uboot_v2_env.XXXXXX")"

tar -C "${PTXDIST_PLATFORMCONFIGDIR}/u-boot-env/" -c . \
	--exclude .svn \
	--exclude .pc \
	--exclude .git \
	--exclude "config.in" \
	--exclude "*/*~" \
	| tar -C "${ENVTMPDIR}" -x

${PTXDIST_SYSROOT_HOST}/bin/ubootenv -s "${ENVTMPDIR}" "${IMAGEDIR}/u-boot-v2-environment"

cp "${IMAGEDIR}/u-boot-v2-environment" "${PTXDIST_SETENV_U_BOOT_V2_ENV}"

rm -rf "${ENVTMPDIR}"
