#! /bin/sh
#
# /etc/init.d/banner
#
# Copyright (C) 2003 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "PTXDIST - release 0.3.25 (2003-09-30)"
echo "Please report problems with this software"
echo "to Robert Schwebel <r.schwebel@pengutronix.de>"
echo 
