#!/bin/sh
#
# /etc/init.d/cleanup-logs
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "cleaning up logfiles... "

if [ ! -d /data/log ]; then /bin/mkdir /data/log; fi
if [ ! -d /data/tmp ]; then /bin/mkdir /data/tmp; fi

/bin/rm -f /var/log/messages.old
if [ -f /var/log/messages ]; then
	/bin/mv /var/log/messages /var/log/messages.old
fi
/bin/echo -n >/var/log/messages

echo "done."

