#!/bin/sh
#
# /etc/init.d/mount-nfs
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "mounting nfs filesystems... "

grep '^nfs-mount:' /data/etc/system.conf | sed 's/^nfs-mount: *//g' |
	while read nfsmount mountpoint; do
		mount -o nfsvers=2,nolock,rsize=4096,wsize=4096 $nfsmount ${mountpoint:-/opt}
	done

echo "done."

