#!/bin/sh
#
# /etc/init.d/network
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "starting network and services... "

if [ ! -e /data/etc/system.conf ]; then
	echo "failed"
	echo "-> no /data/etc/system.conf, disabling eth0"
	exit 0
fi

ipaddr=`grep '^ip-address:' /data/etc/system.conf |
	sed 's/^ip-address: *//g'`
	
/sbin/ifconfig eth0 $ipaddr up

/sbin/utelnetd -d >/dev/null
#/sbin/proftpd -n
echo "done."

