#!/bin/sh
#
# /etc/init.d/network-ppp
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "starting ppp... "

if lsmod | grep n_hdlc >/dev/null; then
	echo -n "[modules already loaded] "
else
	insmod slhc
	insmod ppp_generic
	insmod ppp_synctty
	insmod n_hdlc
fi

echo "done."
