#!/bin/sh
#
# /etc/init.d/nfs-server
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

nfsd=`grep '^nfs-server:' /data/etc/system.conf |
	sed 's/^nfs-server: *//g'`

if [ "_$nfsd" = "_yes" -a -e /etc/exports ]; then
	echo -n "starting NFS server... "
	/sbin/portmap
	/sbin/nfsd 2
	/sbin/mountd
	/sbin/exportfs -a
	echo "done." 
fi

