#!/bin/sh
#
# /etc/init.d/root-remount
#

type=`/bin/cat /proc/mounts | grep "^/dev/root " | cut "-d " -f3`

if [ "_$type" != "_cramfs" ]; then
	echo -n "remounting root filesystem read/write... "
	mount -o remount,rw /dev/root /
	echo "done."
fi

