#!/bin/sh
#
# /etc/init.d/sys-config
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "basic system configuration... "
# /usr/bin/yes | /sbin/e2fsck /dev/ide/host0/bus0/target0/lun0/part1
/bin/hostname localhost
ifconfig lo 127.0.0.1 up
echo "done."

