#!/bin/sh
#
# /etc/init.d/syslog
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Kai-Uwe Bloem <linux-development@auerswald.de>
#

echo -n "starting the system logger... "
/sbin/klogd
/sbin/syslogd
sleep 1 # wait for syslogd to settle before shutting console klogging up
echo 0 >/proc/sys/kernel/printk
echo "done."

