#!/bin/sh
#
# /etc/init.d/usbnet
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "starting USB network port ... "

#if [ ! -e /data/etc/system.conf ]; then
#	echo "failed"
#	echo "-> no /data/etc/system.conf, disabling usb0"
#	exit 0
#fi

module_path=/lib/modules/2.4.19-rmk7-pxa2-ptx13/kernel/drivers/usb/gadget

echo
echo -n "loading modules ..."
insmod $module_path/pxa2xx_udc.o
insmod $module_path/rndis.o
insmod $module_path/g_ether.o
echo "done"

echo -n "setting up usb0 port ..."

# FIXME: integrate this with Auerswald config system
# ipaddr=`grep '^ip-address:' /data/etc/system.conf |
# 	sed 's/^ip-address: *//g'`

# take IP address from RFC3330 Local Link space
ipaddr=169.254.0.1
 
/sbin/ifconfig usb0 $ipaddr up

echo "done."

echo -n "starting DHCP server on usb0 ..."
/usr/sbin/udhcpd /etc/udhcpd.conf
echo "done."


