#!/bin/sh

MACHINE_ID="/etc/machine-id"

if mount | grep -q "${MACHINE_ID}"; then
	umount "${MACHINE_ID}" &&
	rm "${MACHINE_ID}"
fi &&

dbus-uuidgen --ensure="${MACHINE_ID}" &&
chmod 0444 "${MACHINE_ID}"

