#!/bin/sh
#
# /etc/init.d/banner
#
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "PTXdist-0.5.2-cvs (2004-06-30T10:50:59+0200)"
echo 
host=`/bin/hostname`
/usr/sbin/figlet -f /usr/share/figlet/standard "PII $host"
echo
echo

