#!/bin/bash

# find out which version of busybox we have; this is taken from the name
# of this directory

bb_version=$(echo $(basename $(pwd)) | sed -e "s/busybox-//g")
bb_path=/tmp/busybox-${bb_version}

#
# first extract all configuration files from the original source tree
#

for cfgfile in $(find ${bb_path} -name "Config.in"); do
	new_cfgfile=$(echo $cfgfile | sed -e "s~${bb_path}~\.~g")
	dir=$(echo $new_cfgfile | sed -e "s~Config\.in~~g")
	mkdir -p $dir
	../../scripts/mkprefix -v -p BB_CONFIG_ < $cfgfile > $new_cfgfile
done

#
# fix some entries 
# 

echo "---------------------------------------------------------------------\n";
echo "Fixing some stuff...\n";
echo "---------------------------------------------------------------------\n";

for cfgfile in $(find . -name "Config.in"); do

	sed -i -e "s/^source \(.*\)/source config\/busybox-${bb_version}\/\1/g" $cfgfile
	sed -i -e "s/^mainmenu \(.*$\)/# mainmenu \1/g" $cfgfile
	sed -i -e "s/^\(menu .*\)$/\1\n  depends on BUSYBOX/g" $cfgfile

done

