#!/bin/sh
#
# /etc/init.d/mount-local
#
# Configuration for Auerswald Innokom
#
# Copyright (C) 2003 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "mounting filesystems... "
mount -a 
echo "done."

