#!/bin/sh
#
# /etc/init.d/usbnet
#
# Copyright (C) 2003 Auerswald GmbH & Co. KG
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "starting USB network port ... "

if [ ! -e /data/etc/usb.conf ]; then
	echo "failed"
	echo "-> no /data/etc/usb.conf, disabling usb0"
	exit 0
fi

if lsmod | grep g_ether >/dev/null; then
	echo -n "[modules already loaded] "
else
	echo
	insmod pxa2xx_udc
	insmod rndis
	insmod g_ether
fi

ipaddr=`grep '^ip-address:' /data/etc/usb.conf |
 	sed 's/^ip-address: *//g'`
netmask=`grep '^net-mask:' /data/etc/usb.conf |
	sed 's/^net-mask: *//g'`
dhcp=`grep '^dhcp-server:' /data/etc/usb.conf |
	sed 's/^dhcp-server: *//g'`

# take IP address from RFC3330 Local Link space if not set
if [ -z "$ipaddr" ]; then	ipaddr=169.254.0.1; netmask=255.255.0.0; fi

# calculate address for the remote USB station
remaddr=`echo $ipaddr | tr '.' ' ' |
		(read a b c d; echo $a.$b.$c.\`expr $d + 1\`)`
cp /etc/udhcpd.conf /data/etc/udhcpd-usb.conf
echo "interface usb0" >>/data/etc/udhcpd-usb.conf
echo "start $remaddr" >>/data/etc/udhcpd-usb.conf
echo "end   $remaddr" >>/data/etc/udhcpd-usb.conf
if [ -n "$netmask" ]; then
	echo "option subnet $netmask" >>/data/etc/udhcpd-usb.conf
fi
 
killall udhcpd
/sbin/ifconfig usb0 down

if [ -n "$netmask" ]; then	netmask="netmask $netmask"; fi
if [ -n "$ipaddr" ]; then	/sbin/ifconfig usb0 $ipaddr $netmask up; fi
if [ "_$dhcp" = "_yes" ]; then	/usr/sbin/udhcpd /data/etc/udhcpd-usb.conf; fi

echo "done."

