#!/usr/bin/perl

# find out which version of rtai we have; this is taken from the name
# of this directory
$rtai_version = `basename \`pwd\``;
chomp $_version;
$rtai_version =~ s/rtai-//;

#
# first extract all configuration files from the original source tree
#

@configfiles = `find ../../build/rtai*/ -name "Kconfig"`;

while($_ = shift @configfiles) {
	chomp $_;
	my $filename = $_;   $filename =~ s/(.*\/build\/rtai.*?\/)(.*$)/$2/;
	my $dir = $filename; $dir      =~ s/(.*\/)(.*$)/$1/;
	system("mkdir -p $dir");
	system("../../scripts/mkprefix -v -p RTAICFG_ < $_ > $filename");
}


#
# fix some entries 
# 

print "---------------------------------------------------------------------\n";
print "Fixing some stuff...\n";
print "---------------------------------------------------------------------\n";

@fixfiles = `find . -name "Kconfig"`;

while($file = shift @fixfiles) {

	open (FILE, "$file");
	@file = <FILE>;
	close FILE;

	for (@file) { $_ =~ s/^source (.*)/# source $1/g; }
	for (@file) { $_ =~ s/^mainmenu (.*$)/# mainmenu $1/g;           }
	for (@file) { $_ =~ s/^(.*string "Installation directory")//g;    }
	for (@file) { $_ =~ s/^(.*string "Linux source tree")//g;    }
	for (@file) { $_ =~ s,^(.*default "/usr/realtime"),default "\@BUILDDIR@/rtai-build",g;    }
	for (@file) { $_ =~ s,^(.*default "/usr/src/linux"),default "\@KERNEL_DIR@",g;    }

	open (FILE, ">$file");
	print FILE @file;
	close FILE;

}
