#!/bin/sh
#
# /etc/init.d/banner
#

FIGLET="/usr/bin/figlet"
FIGLET_FONTS="/usr/share/figlet"
PATH=/sbin:/bin:/usr/bin

test -f $FIGLET || { echo "$FIGLET not found" >&2 ; exit 1; }

start_proc() {
	echo
	echo "OSELAS(R)-@PROJECT@@PRJVERSION@ (@PTXDIST@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@/@DATE@)"
	echo
	host=`/bin/hostname`
	if [ -n "@VENDOR@" ]; then
		${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "@VENDOR@"
	fi
	${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "$host"
	echo
	echo
}


case "$1" in
        start)
        	start_proc
		;;
	stop)
		# do nothing
		;;
        restart|force-reload)
		start_proc
                ;;
        reload)
                echo "Not supported" >&2
                exit 1
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|force-reload}"
                exit 1
                ;;
esac

exit 0

