#!/bin/sh
#
# /etc/init.d/banner
#
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

FIGLET="/usr/sbin/figlet"
FIGLET_FONTS="/usr/share/figlet"

echo
echo "OSELAS(R)-@PROJECT@@PRJVERSION@ (@PTXDIST@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@/@DATE@)"
echo
host=`/bin/hostname`
if [ -n "@VENDOR@" ]; then
	${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "@VENDOR@"
fi
${FIGLET} -w 0 -f "${FIGLET_FONTS}/standard" "$host"
echo
echo

