#!/bin/sh
#
# This is an inetd init.d script which ist called by init(1) with [start|stop] as argument
#

PATH=/sbin:/bin:/usr/bin
BINARY=/usr/sbin/inetd

# --- nothing to change after this line ---

test -f $BINARY || { echo "$BINARY not found" >&2 ; exit 1; }

start_proc() {
	echo -n "starting inetd..."
	$BINARY
	echo "done"
}

stop_proc() {
	echo -n "stopping inetd..."
	killall inetd
	echo "done"
}


case "$1" in
        start)
        	start_proc
		;;
	stop)
		stop_proc
		;;
        restart|force-reload)
                echo -n "restarting inetd..."
                stop_proc
		sleep 2
                start_proc
		echo "done"
                ;;
        reload)
                echo "Not supported" >&2
                exit 1
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|force-reload}"
                exit 1
                ;;
esac

exit 0

