#!/bin/sh

#
# lighttpd
#
PATH=/usr/bin:/usr/sbin:/bin:/sbin

PREFIX="lighttpd: "
LIGHTTPD="/usr/sbin/lighttpd"
LIGHTTPD_CONF="/etc/lighttpd/lighttpd.conf"

case $1 in

	start)
		echo "${PREFIX}starting"

		if [ \! -d /var/log/lighttpd ]; then
			mkdir -p /var/log/lighttpd
			chown www:www /var/log/lighttpd
		fi

		if start-stop-daemon --start --quiet --oknodo --exec ${LIGHTTPD} -- -f ${LIGHTTPD_CONF}; then
			echo "${PREFIX}done"
		else
			echo "${PREFIX}error, could not start server"
		fi
		;;

	stop)
		echo "${PREFIX}stoppping"

		if start-stop-daemon --stop --quiet --oknodo --exec ${LIGHTTPD}; then
			echo "${PREFIX}done"
		else
			echo "${PREFIX}error, could not stop server"
		fi
		;;

	*)
		echo "${PREFIX}usage: ${0} [start|stop]"
		exit 1
		;;

esac
