#!/bin/sh
#
# /etc/init.d/net2flash: 
#

ROOTFS="/dev/mtdblock/2"

case $1 in 

	start)
		# check if we already run from flash	
		if [ "x`mount | grep root | grep mtdblock`" != "x" ]; then
			echo "net2flash does only work when running from NFS";
			exit 1;
		fi
		# check if /mnt is already in use
		if [ "x`mount | grep /mnt`" != "x" ]; then
			echo "mountpoint /mnt already in use";
			exit 1;
		fi

		echo -n "mounting $ROOTFS..."
		mount -t jffs2 $ROOTFS /mnt
		if [ "$?" != "0" ]; then
			echo "could not mount $ROOTFS on /mnt"
			exit 1
		fi
		echo "done"
		echo -n "save /home..."
		cp -a /mnt/home /tmp
		echo "done"
		echo -n "cleaning old content..."
		rm -fr /mnt/*
		echo "done"
		echo -n "copying files..."
		cp -ax / /mnt/
		echo "done"
		echo -n "generating md5 sums..."
		rm -f /tmp/files.md5
		cd /mnt
		find . -type f | xargs md5sum > /tmp/files.md5
		echo "done"
		echo -n "checking md5sums..."
		cd /;
		failures=`md5sum -c /tmp/files.md5 | grep FAILED`
		echo -n "status: " 
		if [ "x$failures" != "x" ]; then
			echo "!!! INCONSISTENCIES DETECTED !!!"
			echo $failures
		else
			echo "all files consistent";
		fi
		rm /tmp/files.md5
		echo -n "restore /home..."
		cp -a /tmp/home /mnt/
		echo "done"
		echo -n "unmounting $ROOTFS..."
		umount /mnt
		sync
		echo "done" 
		;;
	*)
		echo "usage: $0 [start|stop]"
		exit 0;
		;;

esac

