#! /bin/sh
### BEGIN INIT INFO
# Provides:          NetworkManager
# Required-Start:    $remote_fs dbus hal
# Required-Stop:     $remote_fs dbus hal
# Should-Start:	     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: network connection manager
# Description:       Daemon for automatically switching network
#		     connections to the best available connection.
### END INIT INFO

set -e

prefix=/usr
exec_prefix=/usr
sbindir=${exec_prefix}/sbin
localstatedir=/var

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="network connection manager"
NAME="NetworkManager"

DAEMON=${sbindir}/$NAME

PIDDIR=${localstatedir}/run
PIDFILE=$PIDDIR/$NAME.pid
CONFFILE=$PIDDIR/$NAME.conf
STATEFILE=$PIDDIR/$NAME.state

DAEMON_OPTS="--config=$CONFFILE --state-file=$STATEFILE"

USER=root

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

test -f /etc/default/NetworkManager && . /etc/default/NetworkManager

#
#	Function that starts the daemon/service.
#
d_start() {
	/lib/init/nm-unmanage.sh

	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--oknodo --user $USER --exec $DAEMON -- $DAEMON_OPTS --pid-file $PIDFILE

}

#
#	Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --retry 5 --quiet --pidfile $PIDFILE \
		 --oknodo --user $USER --exec $DAEMON
 
}


case "$1" in
  start)
	echo "Starting $DESC" "$NAME"
	d_start
	;;
  stop)
	echo "Stopping $DESC" "$NAME"
	d_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC" "$NAME"
	d_stop
	d_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

