#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/sshd
NAME=sshd
PIDFILE=/var/run/sshd.pid

OPENSSH_RSAKEY_DEFAULT="/etc/ssh/ssh_host_rsa_key"
OPENSSH_DSAKEY_DEFAULT="/etc/ssh/ssh_host_dsa_key"

. /lib/init/initmethod-bbinit-functions.sh

test -n "$OPENSSH_RSAKEY" || \
	OPENSSH_RSAKEY=$OPENSSH_RSAKEY_DEFAULT
test -n "$OPENSSH_DSAKEY" || \
	OPENSSH_DSAKEY=$OPENSSH_DSAKEY_DEFAULT

gen_key() {

	key_type=$1
	key_file=$2

	mount_root_rw || exit
	rm -f $key_file > /dev/null 2>&1

	echo -n "generating $key_type key..."
	ssh-keygen -t $key_type -f $key_file -N "" > /dev/null 2>&1

	if [ "$?" = "0" ]; then
		echo "done"
	else
		echo "failed"
		mount_root_restore
		exit 1
	fi

        mount_root_restore || exit
}


case "$1" in

	start)
		mkdir -p /var/run/sshd

		# create keys if necessary
		[ \! -f "$OPENSSH_RSAKEY" ] && gen_key rsa "$OPENSSH_RSAKEY"
		[ \! -f "$OPENSSH_DSAKEY" ] && gen_key dsa "$OPENSSH_DSAKEY"

		echo -n "starting sshd..."
		start-stop-daemon -S -x "$DAEMON" -p "$PIDFILE" > /dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "done"
		else
			echo "failed"
			exit 1
		fi
		;;

	stop)
		echo -n "stopping sshd..."
		start-stop-daemon -K -p $PIDFILE > /dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "done"
		else
			echo "failed"
			exit 1
		fi
		;;

	restart|force-reload)
		echo -n "restarting sshd..."
		start-stop-daemon -K -x "$DAEMON" -p $PIDFILE > /dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "done"
		else
			echo "failed"
			exit 1
		fi
		sleep 1
		start-stop-daemon -S -x "$DAEMON" -p $PIDFILE > /dev/null 2>&1
		if [ "$?" = "0" ]; then
			echo "done"
		else
			echo "failed"
			exit 1
		fi
		;;

	*)
		echo "Usage: $0 {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0

