#!/bin/sh
#
# /etc/init.d/rcS
#
# $Id$
#

echo -n "mounting filesystems..."
mount -a 2>/dev/null
echo "done."

# modprobe ppp_async
# loadkmap < /etc/boottime.kmap

# set hostname
test -e /etc/hostname && hostname -F /etc/hostname

echo "running rc.d services..."
run-parts -a start /etc/rc.d
