#!/bin/sh
#
# /etc/init.d/telnetd
#
# $Id$
#

if [ -f /usr/sbin/telnetd ]; then
	echo "Starting telnetd..."
	/usr/sbin/telnetd
	exit 0
fi

if [ -f /sbin/utelnetd ]; then
	echo "Starting utelnetd..."
	/sbin/utelnetd -d
	exit 0
fi

echo "No telnetd found. Aborting"

