#!/bin/bash

echo "config............: `basename \`pwd\``" >&5
echo "date..............: `date`" >&5
echo "user..............: ${USER}@${HOSTNAME}" >&5

PTX_STARTTIME=`date +"%s"`

ln -sf /ptx/src
ptxdist go

PTX_RETVAL=$?

PTX_STOPTIME=`date +"%s"`

let "PTX_TIME=$PTX_STOPTIME-$PTX_STARTTIME"
let "PTX_TIME_H=$PTX_TIME/3600"
let "PTX_TIME_M=($PTX_TIME-$PTX_TIME_H*3600)/60"
let "PTX_TIME_S=($PTX_TIME-$PTX_TIME_H*3600-$PTX_TIME_M*60)/60"

echo "buildtime........: `${PTX_TIME_H}h${PTX_TIME_M}m${PTX_TIME_S}s`" >&5

echo "result...........: ${PTX_RETVAL}" >&5

