--- ptxdist-0.7-trunk/rules/Rules.make	Fri Aug  5 11:09:31 2005
+++ ptxdist-0.7.5-kub/rules/Rules.make	Mon Jul 11 13:07:43 2005
@@ -111,20 +111,21 @@
 #
 # FIXME: Consolidate a bit more
 #
+CROSS_BIN = $(call remove_quotes,$(DISTCC_PATH_COLON))$(call remove_quotes,$(PTXCONF_PREFIX))/bin
 ifndef NATIVE
 COMPILER_PREFIX		= $(call remove_quotes,$(PTXCONF_COMPILER_PREFIX))
 endif
-CROSS_AR		= $(COMPILER_PREFIX)ar
-CROSS_AS		= $(COMPILER_PREFIX)as
-CROSS_LD		= $(COMPILER_PREFIX)ld
-CROSS_NM		= $(COMPILER_PREFIX)nm
-CROSS_CC		= $(COMPILER_PREFIX)gcc
-CROSS_CXX		= $(COMPILER_PREFIX)g++
-CROSS_RANLIB		= $(COMPILER_PREFIX)ranlib
-CROSS_OBJCOPY		= $(COMPILER_PREFIX)objcopy
-CROSS_OBJDUMP		= $(COMPILER_PREFIX)objdump
-CROSS_STRIP		= $(COMPILER_PREFIX)strip
-CROSSSTRIP		= $(CROSS_STRIP)
+CROSS_AR		= $(CROSS_BIN)/$(COMPILER_PREFIX)ar
+CROSS_AS		= $(CROSS_BIN)/$(COMPILER_PREFIX)as
+CROSS_LD		= $(CROSS_BIN)/$(COMPILER_PREFIX)ld
+CROSS_NM		= $(CROSS_BIN)/$(COMPILER_PREFIX)nm
+CROSS_CC		= $(CROSS_BIN)/$(COMPILER_PREFIX)gcc
+CROSS_CXX		= $(CROSS_BIN)/$(COMPILER_PREFIX)g++
+CROSS_RANLIB		= $(CROSS_BIN)/$(COMPILER_PREFIX)ranlib
+CROSS_OBJCOPY		= $(CROSS_BIN)/$(COMPILER_PREFIX)objcopy
+CROSS_OBJDUMP		= $(CROSS_BIN)/$(COMPILER_PREFIX)objdump
+CROSS_STRIP		= $(CROSS_BIN)/$(COMPILER_PREFIX)strip
+CROSSSTRIP		= $(CROSS_BIN)/$(CROSS_STRIP)
 
 CROSS_ENV_AR		= AR=$(CROSS_AR)
 CROSS_ENV_AS		= AS=$(CROSS_AS)
