#!/bin/sh
#
# /etc/init.d/root-remount
#
# Configuration for Rayonic
#
# 2002/10/03    Robert Schwebel <r.schwebel@pengutronix.de>
#

echo "remounting root filesystem read/write..."
mount -o remount,rw /dev/root /
echo "done."
