#!/bin/sh
#
# /etc/init.d/rcS
#
# Configuration for Cameron EFCO
#
# 2003/12/20 Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "mounting filesystems..."
mount -a 
echo "done."

echo -n "creating links in /dev..."
ln -s /dev/vc/0 /dev/tty0
ln -s /dev/vc/1 /dev/tty1
ln -s /dev/vc/2 /dev/tty2
ln -s /dev/vc/3 /dev/tty3
ln -s /dev/vc/4 /dev/tty4
ln -s /dev/vc/5 /dev/tty5
ln -s /dev/vc/6 /dev/tty6
ln -s /dev/vc/7 /dev/tty7
ln -s /dev/vc/8 /dev/tty8
ln -s /dev/vc/9 /dev/tty9
ln -s /dev/fb/0 /dev/fb0
echo "done."

# echo "loading keymap..."
# loadkmap < /etc/boottime.kmap
# echo "done."
