#!/bin/sh
#
# /etc/init.d/banner
#
# Copyright (C) 2004 Pengutronix
# Robert Schwebel <r.schwebel@pengutronix.de>
#

echo
echo "@PROJECT@@PRJVERSION@ (@PTXDIST@-@VERSION@.@PATCHLEVEL@.@SUBLEVEL@@EXTRAVERSION@/@DATE@)"
echo
host=`/bin/hostname`
/usr/sbin/figlet -f /usr/share/figlet/standard "@VENDOR@$host"
echo
echo

