Document: ptxdist
Title: Debian ptxdist Manual
Author: <insert document author here>
Abstract: This manual describes what ptxdist is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ptxdist/ptxdist.sgml.gz

Format: postscript
Files: /usr/share/doc/ptxdist/ptxdist.ps.gz

Format: text
Files: /usr/share/doc/ptxdist/ptxdist.text.gz

Format: HTML
Index: /usr/share/doc/ptxdist/html/index.html
Files: /usr/share/doc/ptxdist/html/*.html

  
