#!/bin/sh
# example configuration for network interfaces:
# ---------------------------------------------
# possible options for udhcpc:
# -c,     --clientid=CLIENTID     Client identifier
# -H,     --hostname=HOSTNAME     Client hostname
# -b,     --background    Fork to background if lease cannot be immediately negotiated.
# -n,     --now   Exit with failure if lease cannot be immediately negotiated.
# -q,     --quit  Quit after obtaining lease
# -r,     --request=IP    IP address to request (default: none)
# -s,     --script=file   Run file at dhcp events (default: /usr/share/udhcpc/default.script)

# eth0
#ifconfig eth0 192.168.42.1 netmask 255.255.255.0 broadcast 192.168.42.255 up
ifconfig eth0 up ; /sbin/udhcpc -i eth0 -b 

# eth1
ifconfig eth1 192.168.23.1 netmask 255.255.255.0 broadcast 192.168.23.255 up
# ifconfig eth1 up; /sbin/udhcpc -i eth1 -b  

# default route
# route add default eth0
# route add default gw 192.168.42.254 
