#!/bin/sh
#
# File:
# chat-gprs-disconnect
#
# send break
exec /usr/sbin/chat -V -s -S	\
ABORT		"BUSY"		\
ABORT		"ERROR"		\
ABORT		"NO DIALTONE"	\
SAY		"\nSending break to the modem\n"	\
""		"\K"		\
""		"+++ATH"	\
SAY		"\nPDP context detached\n"
