#!/bin/sh
#
# /etc/init.d/dropbear
#
# Configuration for BMW
#
# 2004/02/28 Robert Schwebel <r.schwebel@pengutronix.de>
#

case $1 in

	start)
		echo "checking for host key..."
		if [ ! -f /etc/dropbear/dropbear_dss_host_key ]; then
			echo "creating new host key..."
			/usr/bin/dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key
		fi
		echo "starting dropbear daemon..."
		/usr/sbin/dropbear
		echo "done."
		;;
	stop)
		echo "killing dropbear daemon..."
		killall dropbear
		echo "done."
		;;
	*)
		echo "usage: $0 [start|stop]"
		;;
esac

