#!/bin/sh
#
# /etc/init.d/ppp
#
# Configuration for BMW
#
# 2004/02/27 Robert Schwebel <r.schwebel@pengutronix.de>
#

case $1 in

	start)
		echo "loading ppp drivers:"
		/sbin/modprobe slhc
		/sbin/modprobe ppp_generic
		/sbin/modprobe ppp_async
		/sbin/modprobe ppp_deflate
		/sbin/modprobe bsd_comp
		echo "done."
		;;
	stop)
		echo "removing ppp drivers:"
		/sbin/rmmod bsd_comp
		/sbin/rmmod ppp_deflate
		/sbin/rmmod ppp_async
		/sbin/rmmod ppp_generic
		/sbin/rmmod slhc
		echo "done."
		;;
	*)
		echo "usage: $0 [start|stop]"
		;;
esac

