#!/bin/sh
#
# /etc/init.d/xfree86
#
# Configuration for BMW
#
# 2004/03/28 Robert Schwebel <r.schwebel@pengutronix.de>
#

USE_IDRIVE=1;		# 1=iDrive, 0= PS2 mouse
export IDRIVE_NAMED_PIPE=/tmp/idrive.fifo

case $1 in

        start)
		if [ "x`pidof X`" != "x" ]; then
			echo "X server already running, exiting.";
			exit 1;
		fi;
                echo "faking some directories..."
		mkdir /tmp/ptxdist-bmwm-rsc
		mkdir /tmp/ptxdist-bmwm-rsc/i386-unknown-linux-gnu
		ln -sf /etc /tmp/ptxdist-bmwm-rsc/i386-unknown-linux-gnu/
		echo "loading event driver..."
		[ `grep evdev /proc/modules` ] ||
			insmod /lib/modules/2.6.1/kernel/drivers/input/evdev.ko
		echo "loading mouse driver..."
		if [ "$USE_IDRIVE" = "1" ]; then
		#	[ `grep pcan_drvd /proc/modules` ] ||
		#		insmod /lib/modules/2.6.1/kernel/drivers/input/idrive/pcan_drvd.ko;
			[ `grep pcan_drv /proc/modules` ] ||
				insmod /lib/modules/2.6.1/kernel/drivers/input/idrive/pcan_drv.ko;
			[ `grep idrive /proc/modules` ] ||
				insmod /lib/modules/2.6.1/kernel/drivers/input/idrive/idrive.ko;
				/usr/local/bin/userIDrive /dev/input/event1 & 
		else
			[ `grep psmouse.ko /proc/modules` ] ||
				insmod /lib/modules/2.6.1/kernel/drivers/input/mouse/psmouse.ko;
		fi
		echo "starting X server..."
		unset DISPLAY
		/usr/X11R6/bin/X -br -mouse /dev/input/event1,5 -s 0 -screen 320x240x24 &
		echo $! > /var/run/xfree86.pid
		# wait for X server to have started
		while !(netstat -tan | grep ":6000" > /dev/null); do
			echo foo > /dev/null;
		done
                echo "done."
                ;;
        stop)
                echo "killing X server..."
		kill `cat /var/run/xfree86.pid`
		echo "removing drivers..."
		rmmod psmouse > /dev/null 2>&1 
		rmmod pcan_drvd > /dev/null 2>&1 
		rmmod evdev > /dev/null 2>&1
                echo "done."
                ;;

	restart)
		/etc/init.d/xfree86 stop
		/etc/init.d/xfree86 start
		;;

        *)
                echo "usage: $0 [start|stop]"
                ;;
esac



