#!/bin/sh
#
# /etc/init.d/rcS
#
# 2004-06-17 Robert Schwebel <r.schwebel@pengutronix.de>
#

echo -n "mounting filesystems..."
mount -a 2>/dev/null
echo "done."

# modprobe ppp_async
# loadkmap < /etc/boottime.kmap

# set hostname 
test -e /etc/hostname && hostname -F /etc/hostname

echo -n "creating Network-Device lo..."
ifconfig lo up 127.0.0.1
echo "done."

echo "running rc.d services..."
for i in /etc/rc.d/* ; do
	echo "[ $i ] ..." 
	$i || echo "*** FAILED ***" 
done;

