#!/bin/bash

# $1: compiler path
# $2: configuration name
# $3: logfile

PATH=$1:$PATH 

echo config...: $2 >> $3
echo date.....: `date` >> $3
echo user.....: $USER@$HOSTNAME >> $3

make $2_config

if [ $? != "0" ]; then 
	echo "result...: no config file '$2'" >> $3
	echo >> $3
	exit 1
fi

make oldconfig

#
# Now start the compilation
#

PTX_STARTTIME=`date +"%s"`
(make world; echo PTX_RESULT=$?) 2>&1 | tee logfile
PTX_STOPTIME=`date +"%s"`
PTX_RESULT=`grep PTX_RESULT logfile | awk -F"=" -- '{print $2}'`
let "PTX_TIME=$PTX_STOPTIME-$PTX_STARTTIME"

PTX_BUILDTIME_H=$(($PTX_TIME/3600))
PTX_TIME=$(($PTX_TIME-$PTX_BUILDTIME_H*3600))
PTX_BUILDTIME_M=$(($PTX_TIME/60))
PTX_TIME=$(($PTX_TIME-$PTX_BUILDTIME_M*60))
PTX_BUILDTIME_S=$PTX_TIME

echo buildtime: ${PTX_BUILDTIME_H}h${PTX_BUILDTIME_M}m${PTX_BUILDTIME_S}s >> $3
echo result...: $PTX_RESULT >> $3
echo >> $3

# save logfile
logfile logs/$2.log

# save root filesystem 
# FIXME: use image mechanism...
tar -zcvf logs/$2-root.tar.gz root

make distclean
	

