#!/bin/bash

# $1: compiler path
# $2: configuration name

PATH=$1:$PATH 

make $2_config
make oldconfig

echo config...: $2 >> COMPILE-TEST
echo date.....: `date` >> COMPILE-TEST
echo user.....: $USER@$HOSTNAME >> COMPILE-TEST

#
# Now start the compilation
#

PTX_STARTTIME=`date +"%s"`
(make world; echo PTX_RESULT=$?) 2>&1 | tee logfile
PTX_STOPTIME=`date +"%s"`
PTX_RESULT=`grep PTX_RESULT logfile | awk -F"=" -- '{print $2}'`
let "PTX_TIME=$PTX_STOPTIME-$PTX_STARTTIME"

PTX_BUILDTIME_H=$(($PTX_TIME%60))
PTX_TIME=$(($PTX_TIME-$PTX_BUILDTIME_H*60))
PTX_BUILDTIME_M=$(($PTX_TIME%60))
PTX_TIME=$(($PTX_TIME-$PTX_BUILDTIME_M*60))
PTX_BUILDTIME_S=$PTX_TIME

echo buildtime: ${PTX_BUILDTIME_H}h${PTX_BUILDTIME_M}m${$PTX_BUILDTIME_S}s >> COMPILE-TEST
echo result...: $PTX_RESULT >> COMPILE-TEST
echo >> COMPILE-TEST

# save logfile in case of an error
[ "$PTX_RESULT" != "0" ] && cp logfile logs/$2.log

# save root filesystem 
# FIXME: use image mechanism...
tar -zcvf logs/$2-root.tar.gz root

make distclean
	

