#!/bin/bash
#
# usage: IMAGES=/image/dir ROOT=/root/dir IPKG=/path/to/ipkg-cl ipkg-test 

PTXDIST_TOPDIR=`pwd`
DIR=`mktemp -d /tmp/ptxdist.XXXXXX`

if [ -z "$IMAGES/*.ipk" ]; then
	echo -e "\nError: please set \$IMAGES to a directory with ipkg packets"
	echo -e "(IMAGES=$IMAGES)\n"
	exit 1
fi

if [ ! -x "$IPKG" ]; then
	echo -e "\nError: \$IPKG must point to an ipkg binary\n"
	echo -e "(IPKG=$IPKG)\n"
	exit 1
fi

for archive in $IMAGES/*.ipk; do
	$IPKG							\
		-f $PTXDIST_TOPDIR/projects/generic/etc/ipkg.conf	\
		-force-depends 					\
		-o $DIR						\
		install $archive 1> /dev/null
done

echo "checking files in ipkg tree..."
cd $DIR
find . | grep -v "./usr/lib/ipkg" | sort -u > $PTXDIST_TOPDIR/logs/root-ipkg.txt

echo "checking files in original tree..."
cd $ROOT
find . | sort -u > $PTXDIST_TOPDIR/logs/root-orig.txt

echo
echo "----------------------------------------------------------------------------"
echo "Result of comparism between ipkg and directly generated tree (good if empty)"
echo "----------------------------------------------------------------------------"
echo

diff -u								\
	$PTXDIST_TOPDIR/logs/root-orig.txt			\
	$PTXDIST_TOPDIR/logs/root-ipkg.txt			\
	> $PTXDIST_TOPDIR/logs/root.diff

cd $PTXDIST_TOPDIR
rm -fr $DIR
cat $PTXDIST_TOPDIR/logs/root.diff >&2
echo

