#!/bin/bash
#
# usage: IMAGES=/image/dir ROOT=/root/dir IPKG=/path/to/ipkg-cl ipkg-test 

SCRIPTDIR=`dirname $0`
. $SCRIPTDIR/libptxdist.sh

if [ -z "$PTXDIST_WORKSPACE" ] ; then
	PTXDIST_WORKSPACE=`pwd`
fi                                                                                                                                      

DIR=`mktemp -d /tmp/ptxdist.XXXXXX`

if [ -z "$IMAGES/*.ipk" ]; then
	echo -e "\nError: please set \$IMAGES to a directory with ipkg packets"
	echo -e "(IMAGES=$IMAGES)\n"
	exit 1
fi

if [ ! -x "$IPKG" ]; then
	echo -e "\nError: \$IPKG must point to an ipkg binary\n"
	echo -e "(IPKG=$IPKG)\n"
	exit 1
fi

for archive in `cd $IMAGES && find . -name "*.ipk"`; do
	$IPKG							\
		-f $ROOT/etc/ipkg.conf				\
		-force-depends 					\
		-o $DIR						\
		install `ptxd_abspath $archive`
#		install $archive 1> /dev/null
done

echo "checking files in ipkg tree..."
cd $DIR
mkdir -p $PTXDIST_WORKSPACE/logs
find . | grep -v "./usr/lib/ipkg" | sort -u > $PTXDIST_WORKSPACE/logs/root-ipkg.txt

echo "checking files in original tree..."
cd $ROOT
find . | sort -u > $PTXDIST_WORKSPACE/logs/root-orig.txt

echo
echo "----------------------------------------------------------------------------"
echo "Result of comparism between ipkg and directly generated tree (good if empty)"
echo "----------------------------------------------------------------------------"
echo

diff -u								\
	$PTXDIST_WORKSPACE/logs/root-orig.txt			\
	$PTXDIST_WORKSPACE/logs/root-ipkg.txt			\
	> $PTXDIST_WORKSPACE/logs/root.diff

cd $PTXDIST_WORKSPACE
rm -fr $DIR
cat $PTXDIST_WORKSPACE/logs/root.diff >&2
echo

