#!/bin/sh

PKGCONFIG=/usr/bin/pkg-config

if [ \! "$SYSROOT" ]; then
	echo >&2
	echo >&2
	echo "pkg-config: missing \$SYSROOT environment variable" >&2
	echo >&2
	echo >&2
	exit 2
fi

#if [ ! "$PKG_CONFIG_LIBDIR" ]; then
#    export PKG_CONFIG_LIBDIR=$SYSROOT/usr/pkgconfig/
#fi

export PKG_CONFIG_LIBDIR
export PKG_CONFIG_PATH
export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1

#
# 1) protect already given sysroot
# 2) add sysroot symbol to all absolute paths
# 3) replace sysroot sign to sysroot path
# 4) libtool isn't correctly DESTDIR/SYSROOT aware, it replaces -lfoo by
#    paths leading to host libraries; using -Wl,-lfoo seems to work. 
# 

OUTPUT=`$PKGCONFIG $*` || exit $?

echo -n $OUTPUT |
	sed -e "s~\-L/*$SYSROOT/*~-L=/~g; s~\-I/*$SYSROOT/*~-I=/~g;" \
	    -e "s~\-L/~-L=/~g; s~\-I/~-I=/~g;"                       \
	    -e "s~\-L\=~-L$SYSROOT~g; s~\-I\=~-I$SYSROOT~g;"         \
	    -e "s~[\t ]\-l~ -Wl,-l~g;"
