#!/bin/sh

PKGCONFIG=/usr/bin/pkg-config

if [ ! "$SYSROOT" ]; then
	echo "pkg-config-filter: missing \$SYSROOT environment variable"
	exit 2
fi

#if [ ! "$PKG_CONFIG_LIBDIR" ]; then
#    export PKG_CONFIG_LIBDIR=$SYSROOT/usr/pkgconfig/
#fi

export PKG_CONFIG_LIBDIR
export PKG_CONFIG_PATH
export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1

[ "$PTXDIST_DEBUG" = "1" ] && echo "$PKGCONFIG $*" >&2

#
# 1) protect already given sysroot
# 2) add sysroot symbol to all absolute paths
# 3) replace sysroot sign to sysroot path
# 4) libtool isn't correctly DESTDIR/SYSROOT aware, it replaces -lfoo by
#    paths leading to host libraries; using -Wl,-lfoo seems to work. 
# 

OUTPUT=`$PKGCONFIG $*` || exit $?

echo -n $OUTPUT |
	sed -e "s~\-L/*$SYSROOT/*~-L=/~g; s~\-I/*$SYSROOT/*~-I=/~g;" | # 1)
	sed -e "s~\-L/~-L=/~g; s~\-I/~-I=/~g;" |                       # 2)
	sed -e "s~\-L\=~-L$SYSROOT~g; s~\-I\=~-I$SYSROOT~g;" |         # 3)
	sed -e "s~[\t ]\-l~ -Wl,-l~g;"                                 # 4)
