#
# Static Variable Definitions for PTXdist
#

PROJECT=PTXdist

PTXDIST_VERSION=0
PTXDIST_PATCHLEVEL=10
PTXDIST_SUBLEVEL=0
PTXDIST_EXTRAVERSION=-svn

PTXDIST_FULLVERSION=${PTXDIST_VERSION}.${PTXDIST_PATCHLEVEL}.${PTXDIST_SUBLEVEL}${PTXDIST_EXTRAVERSION}

