#
# Static Variable Definitions for PTXdist
#

PROJECT=PTXdist

VERSION=0
PATCHLEVEL=10
SUBLEVEL=1
EXTRAVERSION=-svn

FULLVERSION=${VERSION}.${PATCHLEVEL}.${SUBLEVEL}${EXTRAVERSION}

export PROJECT VERSION PATCHLEVEL SUBLEVEL EXTRAVERSION FULLVERSION

