# -*-sh-*-
PATCHDIR=${PTXDIST_TOPDIR}/patches
RULESDIR=${PTXDIST_TOPDIR}/rules
PRERULESDIR=${PTXDIST_TOPDIR}/rules/pre
POSTRULESDIR=${PTXDIST_TOPDIR}/rules/post
SCRIPTSDIR=${PTXDIST_TOPDIR}/scripts
DGENDIR=${SCRIPTSDIR}

PROJECTPATCHDIR=${PTXDIST_WORKSPACE}/patches
PROJECTRULESDIR=${PTXDIST_WORKSPACE}/rules
PROJECTPRERULESDIR=${PTXDIST_WORKSPACE}/rules/pre
PROJECTPOSTRULESDIR=${PTXDIST_WORKSPACE}/rules/post
BUILDDIR=${PTXDIST_WORKSPACE}/build-target
CROSS_BUILDDIR=${PTXDIST_WORKSPACE}/build-cross
HOST_BUILDDIR=${PTXDIST_WORKSPACE}/build-host
STATEDIR=${PTXDIST_WORKSPACE}/state
IMAGEDIR=${PTXDIST_WORKSPACE}/images
ROOTDIR=${PTXDIST_WORKSPACE}/root
ROOTDIR_DEBUG=${PTXDIST_WORKSPACE}/root-debug

PACKAGE_DEP=${STATEDIR}/packages.dep
PACKAGE_URL=${STATEDIR}/packages.url

RULESFILES=${STATEDIR}/rulesfiles
RULESFILES_ALL=${RULESFILES}_all
RULESFILES_MAKE=${RULESFILES}.make
RULESFILES_ALL_MAKE=${RULESFILES_ALL}.make