# -*-sh-*-
PATCHDIR=${PTXDIST_TOPDIR}/patches
RULESDIR=${PTXDIST_TOPDIR}/rules
PRERULESDIR=${PTXDIST_TOPDIR}/rules/pre
POSTRULESDIR=${PTXDIST_TOPDIR}/rules/post
SCRIPTSDIR=${PTXDIST_TOPDIR}/scripts
DGENDIR=${SCRIPTSDIR}

PROJECTPATCHDIR=${PTXDIST_WORKSPACE}/patches
PROJECTRULESDIR=${PTXDIST_WORKSPACE}/rules
PROJECTPRERULESDIR=${PTXDIST_WORKSPACE}/rules/pre
PROJECTPOSTRULESDIR=${PTXDIST_WORKSPACE}/rules/post

# created dirs during build
BUILDDIR=${PTXDIST_PLATFORMDIR}/build-target
CROSS_BUILDDIR=${PTXDIST_PLATFORMDIR}/build-cross
HOST_BUILDDIR=${PTXDIST_PLATFORMDIR}/build-host
PKGDIR=${PTXDIST_PLATFORMDIR}/packages
STATEDIR=${PTXDIST_PLATFORMDIR}/state
IMAGEDIR=${PTXDIST_PLATFORMDIR}/images
ROOTDIR=${PTXDIST_PLATFORMDIR}/root
ROOTDIR_DEBUG=${PTXDIST_PLATFORMDIR}/root-debug

# generated files by "dgen"
PACKAGE_DEP_PRE=${STATEDIR}/packages.dep-pre
PACKAGE_DEP_POST=${STATEDIR}/packages.dep-post

RULESFILES=${STATEDIR}/rulesfiles
RULESFILES_ALL=${RULESFILES}_all
RULESFILES_MAKE=${RULESFILES}.make
RULESFILES_ALL_MAKE=${RULESFILES_ALL}.make

PTX_MAP_ALL_MAKE=${STATEDIR}/ptx_map_all.make

# our config files
PTXCONFIG=${PTXDIST_WORKSPACE}/ptxconfig
PLATFORMCONFIG=${PTXDIST_WORKSPACE}/.platformconfig
