#!/bin/bash
# give project Rulefiles priority and check for existance

PTXDISTRULES="$1"
PROJECTRULES="$2"
FILES="$3"
OUTPUT=""

stripped_names=$(for file in $FILES; do echo "$(basename $file) " ; done | sort -u)

for i in $stripped_names ; do 
if [ -e "$PROJECTRULES/$i" ]; then 
	OUTPUT="$OUTPUT $PROJECTRULES/$i"
else
	if [ -e "$PTXDISTRULES/$i" ]; then 
		OUTPUT="$OUTPUT $PTXDISTRULES/$i"
	fi
fi
done

echo $OUTPUT
