#!/usr/bin/python

import sys
import gnosis.xml.objectify
import re
import datetime

# FIXME: parse CREDITS
authors = {
	'wsa' : 'Wolfram Sang <w.sang@pengutronix.de>',
	'jbe' : 'Juergen Beisert <j.beisert@pengutronix.de>',
	'lfu' : 'Luotao Fu <l.fu@pengutronix.de>',
	'rsc' : 'Robert Schwebel <r.schwebel@pengutronix.de>',
	'jfr' : 'Jochen Frieling <j.frieling@pengutronix.de>',
	'mol' : 'Michael Olbrich <m.olbrich@pengutronix.de>',
	'eric.schumann' : 'Eric Schumann <e.schumann@phytec.de>',
	'mkl' : 'Marc Kleine-Budde <m.kleine-budde@pengutronix.de',
}


xmldoc = gnosis.xml.objectify.XML_Objectify(sys.argv[1])
xmlobj = xmldoc.make_instance()

for l in xmlobj.logentry:

	author = l.author.PCDATA
	if author in authors:
		author = authors[author]

	d = datetime.datetime(*map(int, re.split('[^\d]', l.date.PCDATA)[:-1]))

	if l.msg.PCDATA == None:
		continue

	print "%04i-%02i-%02i %s" % (d.year, d.month, d.day, author)
	print ""

	print l.msg.PCDATA

	print ""

