Subject: mplayer: use BUILD_CC for codec-cfg.c

This patch was taken from OpenEmbedded:
http://www.openembedded.org/filebrowser/org.openembedded.dev/packages/mplayer/files

Signed-off-by: FIXME Get Sign From OE <r.schwebel@pengutronix.de>
Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>

---
 Makefile |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Index: MPlayer-1.0rc2/Makefile
===================================================================
--- MPlayer-1.0rc2.orig/Makefile
+++ MPlayer-1.0rc2/Makefile
@@ -230,7 +230,7 @@ mencoder$(EXESUF): $(MENCODER_DEPS)
 	$(CC) -o $@ $^ $(LDFLAGS_MENCODER)
 
 codec-cfg$(EXESUF): codec-cfg.c codec-cfg.h help_mp.h
-	$(HOST_CC) -I. -DCODECS2HTML $< -o $@
+	$(CC_FOR_BUILD) -I. -DCODECS2HTML $< -o $@
 
 codecs.conf.h: codec-cfg$(EXESUF) etc/codecs.conf
 	./codec-cfg$(EXESUF) ./etc/codecs.conf > $@
