#!/bin/sh
#
# /etc/init.d/httpd
#
# $Id:$
#

NAME=apache2

case "$1" in
    start)
            echo -n "${PREFIX}Starting $NAME: "
	    /usr/sbin/apache2 -d @SERVERROOTPATH@ -k start
            echo "Done"
        ;;

    stop)
            echo -n "${PREFIX}Stopping $NAME: "
	    /usr/sbin/apache2 -d @SERVERROOTPATH@ -k stop
            echo "Done"
        ;;

    reload)
            echo -n "${PREFIX}Restarting $NAME: "
	    /usr/sbin/apache2 -d @SERVERROOTPATH@ -k restart
            echo "Done"
        ;;

    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart"
        exit 1
        ;;
esac

