#!/bin/sh
#
# thttpd
#

PREFIX="thttpd: "
THISFILE=$0
DOCUMENTROOT="/var/www"
thttpd="/usr/sbin/thttpd"
		
usage() {
	echo "${PREFIX}usage: $THISFILE [start|stop]"
}

case $1 in 

	start)
		echo "${PREFIX} starting"
		$thttpd -d $DOCUMENTROOT -u www -nor -nos -p 80 -c '**.cgi' -i /var/run/thttpd.pid -l /var/logs/thttpd.log
		echo "{PREFIX} done"
		;;

	stop)
		echo "${PREFIX} stopping"
		kill -USR1 `cat /var/run/thttpd.pid`
		rm -f /var/run/thttpd.pid
		;;

	*)

		usage
		exit 1
		;;

esac

