#!/bin/bash

. ${PTXDIST_PLATFORMCONFIG}
. "$(dirname "$(readlink -f "$0")")/libwrapper.sh" || exit

cc_check_args "${@}"

cc_add_ld_args
cc_add_fortify
cc_add_stack
cxx_add_extra

exec $0.real "${ARG_LIST[@]}" "$@"
