#!/bin/sh

. "$(dirname "$(readlink -f "$0")")/libwrapper.sh" || exit

export ICECC_VERSION="${ICECC_VERSION_TARGET}"

cc_check_args "${@}"

cc_add_target_ld_args
cc_add_fortify
cc_add_stack
cc_add_pie
cxx_add_target_extra

wrapper_exec "$@"
