#!/bin/sh

. "$(dirname "$(readlink -f "$0")")/libwrapper.sh" || exit

export ICECC_VERSION="${ICECC_VERSION_HOST}"
HOST=true

cc_check_args "${@}"

cc_add_host_ld_args
cxx_add_host_extra
cxx_add_host_icecc "${@}"

wrapper_exec "$@"
