#!/bin/sh
#
# /etc/init.d/rcS
#
# Configuration for fs2
#
# 2004/03/07 Robert Schwebel <r.schwebel@pengutronix.de>
#

# announce that we are there
/etc/init.d/banner

echo -n "mounting filesystems..."
mount -a 
echo "done."

