#!/usr/bin/perl -w 

print "\nCreate new rules file from template:\n";
print "------------------------------------\n\n";

print "Name of new packet..........: "; $packet_name = <STDIN>;
print "Major version number........: "; $major = <STDIN>;
print "Minor version number........: "; $minor = <STDIN>;
print "Micro version number........: "; $micro = <STDIN>;
print "Archive file suffix.........: "; $suffix = <STDIN>;
print "URL of download directory...: "; $url = <STDIN>;
print "PTXdist Packet Author.......: "; $author = <STDIN>;

chop ($packet_name, $major, $minor, $micro, $url, $author, $suffix);
$packet = "xchain-".$packet_name;
$PACKET = uc($packet);
$PACKET =~ s/-/_/;

open(INFILE,  "template-xchain") || die "Can't open template";
open(OUTFILE, ">$packet\.make") || die "Can't open new file";

while (<INFILE>) {
	s,\@PACKET@,$PACKET,g;
	s,\@packet@,$packet,g;
	s,\@packet_name@,$packet_name,g;
	s,\@MAJOR@,$major,g;
	s,\@MINOR@,$minor,g;
	s,\@MICRO@,$micro,g;
	s,\@URL@,$url,g;
	s,\@AUTHOR@,$author,g;
	s,\@SUFFIX@,$suffix,g;
	print OUTFILE $_;
}

close(OUTFILE);
close(INFILE);

print "\n";
