######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 21 07:03:40 2010
######################################################################

TEMPLATE = app
TARGET = @name@
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += @name@.cpp

include(install.pri)

