#
# Simple development makefile
#
.PHONY: all install clean

all: my_executable

CFLAGS=-Werror -Wall

my_executable: my_source.c

clean:
	rm -f my_executable

install:

#
# end of development makefile
#
