#!/bin/sh
#
# /etc/init.d/rcS
#
# Configuration for Frako
#
# 2003/11/20 Robert Schwebel <r.schwebel@pengutronix.de>
#            Benedikt Spranger <b.spranger@pengutronix.de>
# 16.02.2004 Gert Fischer, FRAKO Kondensatoren und Anlagenbau GmbH
#            www.frako.de
#

echo -n "mounting filesystems..."
mount -a 
echo "done."

echo -n "creating links in /dev..."
ln -s /dev/vc/0 /dev/tty0
ln -s /dev/vc/1 /dev/tty1
ln -s /dev/vc/2 /dev/tty2
ln -s /dev/vc/3 /dev/tty3
ln -s /dev/vc/4 /dev/tty4
ln -s /dev/vc/5 /dev/tty5
ln -s /dev/vc/6 /dev/tty6
ln -s /dev/vc/7 /dev/tty7
ln -s /dev/vc/8 /dev/tty8
ln -s /dev/vc/9 /dev/tty9
ln -s /dev/fb/0 /dev/fb0
ln -s /dev/tts/0 /dev/ttyS0
ln -s /dev/tts/1 /dev/ttyS1
chmod 666 /dev/tts/0
chmod 666 /dev/tts/1
echo "done."

#ln -s /home/system/conf /home/frako

modprobe ppp_async
modprobe relais
modprobe lcd_module

loadkmap < /etc/boottime.kmap

echo -n "---creating FRAKO-links in /dev..."
ln -s /dev/misc/lcd /dev/lcd
ln -s /dev/misc/led /dev/led
ln -s /dev/misc/kpd /dev/kpd
chmod 666 /dev/misc/lcd
chmod 666 /dev/misc/led
chmod 666 /dev/misc/kpd

echo -n "---creating Network-Device lo..."
ifconfig lo up 127.0.0.1
echo "done."

echo -n "---creating FRAKO directories and links..."
mkdir /home/frako
chmod 775 /home/frako
chown frako:users /home/frako

mkdir /home/frako/alarm
chmod 755 /home/frako/alarm
chown frako:users /home/frako/alarm

mkdir /home/frako/conf
chmod 755 /home/frako/conf
chown frako:users /home/frako/conf

mkdir /home/frako/up
chmod 775 /home/frako/up
chown frako:users /home/frako/up


mkdir /home/system
chmod 755 /home/system
chown system:users /home/system

mkdir /home/system/alarm
chmod 755 /home/system/alarm
chown system:users /home/system/alarm

mkdir /home/system/conf
chmod 755 /home/system/conf
chown system:users /home/system/conf

mkdir /home/system/history
chmod 755 /home/system/history
chown system:users /home/system/history

mkdir /home/system/temp
chmod 755 /home/system/temp
chown system:users /home/system/temp

mount /home/system/alarm /home/frako/alarm -o bind
mount /home/system/conf  /home/frako/conf -o bind
echo "done."

echo -n "---Bootzeitpunkt festhalten in /home/system/boottime.log..."
date >> /home/system/boottime.log
chown system:users /home/system/boottime.log
sync
echo "done."

